@MiniApi_HostAddress = http://localhost:5236

### Post sample data to the API
POST {{MiniApi_HostAddress}}/data
Content-Type: application/json
Accept: application/json

{
  "Users": [
    {
      "First": "Alice",
      "Last": "Hope",
      "Age": 30.2
    },
    {
      "First": "Bob",
      "Last": "Hope",
      "Age": 42.2
    }
  ],
  "Orders": [
    {
      "Region": "SE",
      "Portfolio": "Low",
      "Value": 300.2
    },
    {
      "Region": "NO",
      "Portfolio": "Low",
      "Value": 400.2
    }
  ]
}

###

### Get debug data from the in-memory database
#GET {{MiniApi_HostAddress}}/debug/db
#Accept: application/json

###